### ISSUE TITLE
window.doge.getBalance() promise hangs

### ISSUE THREAD

**Issue by galenom** [mydoge-com/mydogemask#102]
I have not been able to successfully load an updated balance using `window.doge.getBalance((res) => console.log(res), (err) => console.error(err))` because never fulfills the promise. Attaching a screenshot of the pending state and never changes even after the promise timeout runs. 

<img width="759" alt="Screenshot 2024-11-11 at 2 31 02 PM" src="https://github.com/user-attachments/assets/cf0de442-5369-4407-9372-651a0631735e">

**Comment by alexanvl** [comment]
We're looking into it, will update you ASAP

**Comment by alexanvl** [comment]
Fixed https://github.com/mydoge-com/mydogemask/commit/4f887ef56301dbfaf8832aacecf8848815c58530

**Comment by galenom** [comment]
Super quick. Thank you all!
