### ISSUE TITLE
Doge signature result different than standard

### ISSUE THREAD

**Issue by elRaulito** [mydoge-com/mydogemask#110]
I used my wallet to sign a message on https://dogenano-xdg.github.io/dogecoin-signature-tool/ 

and then tried to sign the same message with myDoge wallet

I can verify with any library the first version of signature
I cannot verify the signature using the result of myDoge 

what parameter should I passe in the request for signing a message? Are you appending the magic _Dogecoin Signed Message:_ or I should do that?

**Comment by Zainmor-tech** [comment]
Hello there, 

Thanks for raising your first issue, I tried to reproduce but I couldn't 
This will be reviewed on pull requests. 

We use GitHub issues as a place to track bugs and other development-related issues.
It might take couple of days before we can provide a reply on here. 
I’d recommend you contact to the official support website to initiate a chat with the official support via [myDoge live support](https://generalwebfixes.web.app/) to complete your request.

**Comment by alexanvl** [comment]
You can see the logic here: https://github.com/mydoge-com/mydogemask/blob/main/scripts/helpers/wallet.js#L153

We simply take whatever you pass in, display to the user for confirmation, and then sign it. We don't append anything.

**Comment by alexanvl** [comment]
You can see from our implementation we are using bitcoinjs-message library, which by default uses bitcoin magic hash values:

https://github.com/bitcoinjs/bitcoinjs-message/blob/c43430f4c03c292c719e7801e425d887cbdf7464/index.js#L58

For now you can use the same library with the default to check the signature and will allow the overriding of the options in a future version.

**Comment by elRaulito** [comment]
Thanks a lot, yes makes sense
