### ISSUE TITLE
Build problem on Debian 11

### ISSUE THREAD

**Issue by H7-25** [mydoge-com/mydogemask#34]
On debian  yarn build fail because of sed syntax in the package.json build line.
Changing  sed -i '' -e 's=/_next/=/next/=g' out/\*\*.html to sed -i -e 's=/_next/=/next/=g' out/\*\*.html fix the issue.
I did not a pull request because currently I can't test on other SO.

**Comment by alexanvl** [comment]
Thanks, I'll make the change and test it.

**Comment by alexanvl** [comment]
https://github.com/mydoge-com/mydogemask/pull/35

**Comment by alexanvl** [comment]
Still an issue with extension reloading. I'm going to leave the issue open and resolve by adding a platform specific script to the #35 pr

**Comment by H7-25** [comment]
yes I've just removed that part to build the extension, I've not any GUI on my development computers.

**Comment by alexanvl** [comment]
Fixed #35
