### ISSUE TITLE
requestTransaction return unexpected data on 0.1.2 release

### ISSUE THREAD

**Issue by H7-25** [mydoge-com/mydogemask#47]
I was testing my integration using a self build extension (version 0.1.0) an requestTransaction was returning as expected : 

 { "txId": "b9fc04f226b194684fe24c786be89cae26abf8fcebbf90ff7049d5bc7fa003f0" }

I've just installed the chrome store release (version 0.1.2) and requestTransaction is now returning unexpected data :

request transaction result {connected: true, address: 'D8vU6PDQ8DacbqFenVFiqWFrmtez9Q9Aor'}

**Comment by H7-25** [comment]
Is there a rate limit on doing request ? I was polling each 10 seconds to keep balance updated , increasing polling interval to 60 seconds look have fixed this issue.

**Comment by alexanvl** [comment]
This sounds like you need to reinstall the extension.

**Comment by alexanvl** [comment]
Am also seeing similar behavior running https://github.com/mydoge-com/mydogemask-next-example 
Looking into it

**Comment by alexanvl** [comment]
Fixed in #51
