### ISSUE TITLE
Error Failed to send transaction

### ISSUE THREAD

**Issue by H7-25** [mydoge-com/mydogemask#52]
After having upgraded to 2.0 from chrome store, for each transaction i get "Failed to send transaction" error message. 
I've try to uninstall and reinstall extension several time but without results. Attached you can find the extension inspector screenshot
![Screenshot 2023-02-12 alle 21 59 03](https://user-images.githubusercontent.com/2895452/218336644-f05265e5-1169-4f2c-8531-080fbcb44007.png)

Chrome version 103.0.5060.134 (Build ufficiale) (arm64)

.

**Comment by alexanvl** [comment]
We aren't able to reproduce this issue. Please provide a code example or a link to a repo where the issue is reproducible.  See the following article for details on submitting a minimal reproducible example: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by H7-25** [comment]
Sorry, there's not step to reproduce or code example to show, at first I thought it was a problem with my website integration, but I've verified and just opening the extension and send a transaction manually is enough to have the error

**Comment by H7-25** [comment]
I've uninstall again the extension and installed the build from GitHub repo and it was working, than I've removed it and reinstalled it again from chrome store and now it work ... 
No way to avoid this kind of problem on updating ? I've done multiple transactions but I was just testing and sending little amounts of doge to another of my wallets but if it happen for a real big transaction it's a really bad problem

**Comment by alexanvl** [comment]
My assumption is it's related to restarting the service worker. In general you shouldn't have issues updating the published release, but it's still possible.  I believe this problem arises when building and loading the extension locally in addition to the published version, but I am guessing as I have not reproduced this specific issue.  Perhaps we can add some documentation on removing the extension, restarting the service worker, etc.
