### ISSUE TITLE
When importing wallet on another device in chrome extension the multiple wallets do not loadin

### ISSUE THREAD

**Issue by Adkdotdoge** [mydoge-com/mydogemask#53]
I added mydoge mask on a second device. the additional wallets that I created do not import and are apparently tied to the same seed phrase from the wallet I generated them on. This may be a big issue if someone loses their device and has to sign in again and has multiple wallets in use.

**Comment by alexanvl** [comment]
Each address is generated deterministically. Simply recreate the addresses and they get generated in the original order.  This is an issue because we do not store any information related to how many addresses a user has generated for a particular phrase.  This is the most secure approach.

**Comment by Adkdotdoge** [comment]
Makes sense. Sheesh. I didn’t want to generate more wallets so I didn’t even try that. 😅
