### ISSUE TITLE
 3d inscription not displayed - You can use "preview" end point instead of "content" to display inscriptions

### ISSUE THREAD

**Issue by minidogenft** [mydoge-com/mydogemask#81]
Hello, 

I just noticed that 3d inscriptions that are not of a "recursive" nature but a direct 3d file, do not display in the wallet. 

I believe this is because of using the "content" endpoint instead of "preview" to display nfts. 

Usually the "preview" endpoint is preferred for display as  "content" may not display at all in some cases but download the raw inscription file instead.

For example, the original dunestone inscription: 

https://wonky-ord.dogeord.io/shibescription/e6a7dbd902af0ceac5ef12b435c8a0374c532d7587e63c8655f669c3cbc316a3i0

If you use the preview endpoint it will display well: 
https://wonky-ord.dogeord.io/preview/e6a7dbd902af0ceac5ef12b435c8a0374c532d7587e63c8655f669c3cbc316a3i0

If you use the content endpoint, it will not display but directly download the 3d file instead:
https://wonky-ord.dogeord.io/content/e6a7dbd902af0ceac5ef12b435c8a0374c532d7587e63c8655f669c3cbc316a3i0

Usually the preview endpoint is used for any display as it scales also tiny inscriptions for a better viewing, also a 3d model collection that would be similar to "runestone" collection on ordinals needs to use the preview endpoint to be rendered.

**Comment by alexanvl** [comment]
@minidogenft noted, we'll update in our next release
